### ISSUE TITLE
Dependancies not installing during initial msm install

### ISSUE THREAD

**Issue by pcwii** [pcwii/usb-music#2]
For some reason the dependencies for this project will not install on picroft
```
dependencies:
  system:
    apt-get: vlc
    apt-get: python3-mutagen
    apt-get: python-pyudev
```

**Comment by pcwii** [comment]
Also not working...
```
dependencies:
  python:
    - mutagen
    - pyudev>=0.21.0
    - vlc
  system:
    apt-get: vlc 
```
